services:
  - type: web
    name: taskflow-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn to_do_manager.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: to_do_manager.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: taskflow-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://taskflow-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://taskflow-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://taskflow-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString

  - type: static_site
    name: taskflow-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://taskflow-backend.onrender.com/api

databases:
  - name: taskflow-db
    databaseName: taskflow
    user: taskflow
